name: build credx

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: install dependencies
        run: bun install

      - name: generate wrangler.jsonc
        run: |
          cat > apps/server/wrangler.jsonc <<EOF
          {
          "name": "untangled-be",
            "account_id": "${{ secrets.CLOUDFLARE_ACCOUNT_ID }}",
            "main": "src/index.ts",
            "compatibility_date": "$(date +%Y-%m-%d)",
            "compatibility_flags": ["nodejs_compat"],
            "vars": {
              "FRONTEND_URL": "${{ vars.FRONTEND_URL }}",
              "REDIS_URL": "${{ secrets.REDIS_URL }}",
              "REDIS_TOKEN": "${{ secrets.REDIS_TOKEN }}",
              "SOLANA_RPC_URL": "${{ secrets.SOLANA_RPC_URL }}",
              "SOLANA_API_KEY": "${{ secrets.SOLANA_API_KEY }}" 
            }
          }
          EOF

      - name: Build all packages
        run: bun run build